#!/bin/bash
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
  echo -e "\033[1;93m-----------------------------------------\033[0m"
  echo -e "CREATE VLESS ACCOUNT           "
  echo -e "\033[1;93m-----------------------------------------\033[0m"

  read -rp "Username : " -e user
  CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

  if [[ ${CLIENT_EXISTS} == '1' ]]; then
    clear
  echo -e "\033[1;93m-----------------------------------------\033[0m"
  echo -e "CREATE VLESS ACCOUNT           "
  echo -e "\033[1;93m-----------------------------------------\033[0m"
    echo ""
    echo "A client with the specified name was already created, please choose another name."
    echo ""
    echo -e "\033[0;34m-----------------------------------------\033[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    m-vless
  fi
done

while true; do
    read -p "Expired  : " masaaktif
    read -p "Limit GB : " Quota
    read -p "Limit IP : " iplimit

    if [[ "$masaaktif" =~ ^[0-9]+$ && "$Quota" =~ ^[0-9]+$ && "$iplimit" =~ ^[0-9]+$ ]]; then
        break
    else
        echo -e "Mohon Untuk Input Angka Saja (tanpa ada huruf atau simbol)"
    fi
done
domain=$(cat /etc/xray/domain)
uuid=$(cat /proc/sys/kernel/random/uuid)
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws&host=${domain}&sni=${domain}#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws&host=${domain}#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/limit/vless/ip
echo -e "$iplimit" > /etc/limit/vless/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^#&" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vless/.vless.db
fi
echo "#& ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vless/.vless.db
clear

mkdir -p /detail/vless/
#Simpan Detail Akun User
cat > /detail/vless/$user.txt <<-END
-----------------------------------------
Xray/Vless Account
-----------------------------------------
Remarks     : ${user}
Domain      : ${domain}
User Quota  : ${Quota} GB
User Ip     : ${iplimit} IP
Port Non TLS: 80,8080,2086,8880
Port TLS    : 443,8443
User ID     : ${uuid}
Encryption  : none
Path TLS    : /vless/multi-path
ServiceName : vless-grpc
-----------------------------------------
Link TLS    : ${vlesslink1}
-----------------------------------------
Link NTLS   : ${vlesslink2}
-----------------------------------------
Link GRPC   : ${vlesslink3}
-----------------------------------------
Format OpenClash : https://${domain}:81/vless-$user.txt
-----------------------------------------
Aktif Selama     : $masaaktif Hari
Dibuat Pada      : $tnggl
Berakhir Pada    : $expe
-----------------------------------------

END

cat >/var/www/html/vless-$user.txt <<-END

-----------------------------------------
Format Open Clash
-----------------------------------------
- name: Vless-$user-WS TLS
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}

- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
  udp: true

- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
  grpc-mode: gun
    grpc-service-name: vless-grpc

-----------------------------------------
Link Akun Vless 
-----------------------------------------
Link TLS      : 
${vlesslink1}
-----------------------------------------
Link none TLS : 
${vlesslink2}
-----------------------------------------
Link GRPC     : 
${vlesslink3}
-----------------------------------------
Expired          : $expe
-----------------------------------------
END

function notif_vl() {
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    export TIME="10"
    export URL="https://api.telegram.org/bot$KEY/sendMessage"
    sensor=$(echo "$user" | sed 's/\(.\{3\}\).*/\1xxx/')
    ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
    TEXT="
<b>-----------------------------------------</b>
<b>TRANSACTION SUCCESSFUL</b>
<b>-----------------------------------------</b>
<b>» Produk : Vless</b>
<b>» ISP :</b> <code>${ISP}</code>
<b>» Limit Quota :</b> <code>${Quota} GB</code>
<b>» Limit Login :</b> <code>${iplimit} Hp</code>
<b>» Username :</b> <code>$sensor</code>
<b>» Duration :</b> <code>${masaaktif} Days</code>
<b>-----------------------------------------</b>
<i>Automatic Notification From Server</i>
<b>-----------------------------------------</b>
"
    curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
notif_vl
systemctl restart xray > /dev/null 2>&1
systemctl restart nginx > /dev/null 2>&1
sleep 0.5
clear
echo -e ""
echo -e "\033[1;93m-----------------------------------------\033[0m"
echo -e "Xray/Vless Account"
echo -e "\033[1;93m-----------------------------------------\033[0m"
echo -e "Remarks     : ${user}"
echo -e "Domain      : ${domain}"
echo -e "User Quota  : ${Quota} GB"
echo -e "User Ip     : ${iplimit} IP"
echo -e "Port Non TLS: 80,8080,2086,8880"
echo -e "Port TLS    : 443,8443"
echo -e "User ID     : ${uuid}"
#echo -e "Xray Dns.   : ${NS}"
#echo -e "Pubkey.     : ${PUB}"
echo -e "Encryption  : none"
echo -e "Path TLS    : /vless/multi-path "
echo -e "ServiceName : vless-grpc"
echo -e "\033[1;93m-----------------------------------------\033[0m"
echo -e "Link TLS    : ${vlesslink1}"
echo -e "\033[1;93m-----------------------------------------\033[0m"
echo -e "Link NTLS   : ${vlesslink2}"
echo -e "\033[1;93m-----------------------------------------\033[0m"
echo -e "Link GRPC   : ${vlesslink3}"
echo -e "\033[1;93m-----------------------------------------\033[0m"
echo -e "Format OpenClash : https://${domain}:81/vless-$user.txt"
echo -e "\033[1;93m-----------------------------------------\033[0m"
echo -e "Aktif Selama     : $masaaktif Hari"
echo -e "Dibuat Pada      : $tnggl"
echo -e "Berakhir Pada    : $expe"
echo -e "\033[1;93m-----------------------------------------\033[0m"
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
m-vless