#!/bin/bash
clear
y='\033[1;33m'
BIWhite='\033[1;97m'
BIGreen='\033[1;92m'
BIYellow='\033[1;93m'
IGreen='\033[0;92m'
NC='\033[0m'

# Membuat file reboot_otomatis jika tidak ada
if [ ! -e /usr/local/bin/reboot_otomatis ]; then
    cat << EOF > /usr/local/bin/reboot_otomatis
#!/bin/bash
tanggal=\$(date +"%m-%d-%Y")
waktu=\$(date +"%T")
echo "Server successfully rebooted on the date of \$tanggal hit \$waktu." >> /root/log-reboot.txt
/sbin/shutdown -r now
EOF
    chmod +x /usr/local/bin/reboot_otomatis
fi

# Menu Utama
clear
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo -e "${BIYellow}AUTOREBOOT MANAGER${NC}"
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo -e "${IGreen}[${BIWhite}01${IGreen}] ${NC}${BIWhite}Set autoreboot Every 1 Hour${NC}"
echo -e "${IGreen}[${BIWhite}02${IGreen}] ${NC}${BIWhite}Set autoreboot Every 6 Hours${NC}"
echo -e "${IGreen}[${BIWhite}03${IGreen}] ${NC}${BIWhite}Set autoreboot Every 12 Hours${NC}"
echo -e "${IGreen}[${BIWhite}04${IGreen}] ${NC}${BIWhite}Set autoreboot Every 1 Day${NC}"
echo -e "${IGreen}[${BIWhite}05${IGreen}] ${NC}${BIWhite}Set autoreboot Every 1 Week${NC}"
echo -e "${IGreen}[${BIWhite}06${IGreen}] ${NC}${BIWhite}Set autoreboot Every 1 Month${NC}"
echo -e "${IGreen}[${BIWhite}07${IGreen}] ${NC}${BIWhite}Disable autoreboot${NC}"
echo -e "${IGreen}[${BIWhite}08${IGreen}] ${NC}${BIWhite}View Reboot Log${NC}"
echo -e "${IGreen}[${BIWhite}09${IGreen}] ${NC}${BIWhite}Remove Reboot Log${NC}"
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo -e "${BIYellow}Input x or [ Ctrl+C ] • To-${BIWhite}Exit${NC}"
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo ""

# Input Pilihan Menu
read -p "Select menu: " x

# Validasi Input Menu
case $x in
    1)
        echo "10 * * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
        echo "Autoreboot has been set every 1 hour."
        read -n 1 -s -r -p "Press any key to return to the menu"
        autoreboot
        ;;
    2)
        echo "10 */6 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
        echo "Autoreboot has been set every 6 hours."
        read -n 1 -s -r -p "Press any key to return to the menu"
        autoreboot
        ;;
    3)
        echo "10 */12 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
        echo "Autoreboot has been set every 12 hours."
        read -n 1 -s -r -p "Press any key to return to the menu"
        autoreboot
        ;;
    4)
        echo "10 0 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
        echo "Autoreboot has been set once a day."
        read -n 1 -s -r -p "Press any key to return to the menu"
        autoreboot
        ;;
    5)
        echo "10 0 */7 * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
        echo "Autoreboot has been set once a week."
        read -n 1 -s -r -p "Press any key to return to the menu"
        autoreboot
        ;;
    6)
        echo "10 0 1 * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
        echo "Autoreboot has been set once a month."
        read -n 1 -s -r -p "Press any key to return to the menu"
        autoreboot
        ;;
    7)
        rm -f /etc/cron.d/reboot_otomatis
        echo "Autoreboot has been disabled."
        read -n 1 -s -r -p "Press any key to return to the menu"
        autoreboot
        ;;
    8)
        clear
        if [ -e /root/log-reboot.txt ]; then
            echo -e "${BIWhite}─────────────────────────────────────${NC}"
            echo -e "${BIYellow}AUTOREBOOT LOG${NC}"
            echo -e "${BIWhite}─────────────────────────────────────${NC}"
            cat /root/log-reboot.txt
            echo -e "${BIWhite}─────────────────────────────────────${NC}"
        else
            echo "No reboot activity found."
        fi
        read -n 1 -s -r -p "Press any key to return to the menu"
        autoreboot
        ;;
    9)
        echo "" > /root/log-reboot.txt
        echo "Auto Reboot Log successfully deleted!"
        read -n 1 -s -r -p "Press any key to return to the menu"
        autoreboot
        ;;
    x | X)
        clear
        menu
        ;;
    *)
        echo "Invalid option, please try again."
        ;;
esac